version: 2.1
executors:
  toxandnode:
    working_directory: ~/project
    docker:
      - image: girder/tox-and-node
      - image: memcached
      - image: circleci/mongo:4.0-ram
      - image: rabbitmq
commands:
  dependencies:
    description: "Install openssl library"
    steps:
      - run: 
          name: Update package list
          command: apt update -y
      - run: 
          name: Install openssl and libvip dependencies
          command: apt install libcurl4-openssl-dev libssl-dev build-essential pkg-config libglib2.0-dev libexpat1-dev -y
      - run:
          name: Download libvip library
          command: wget https://github.com/libvips/libvips/releases/download/v8.11.2/vips-8.11.2.tar.gz
      - run:
          name: Configure libvip library
          command: tar xf vips-8.11.2.tar.gz && cd vips-8.11.2 && ./configure
      - run:
          name: Install libvip library
          command: make && make install && ldconfig

  tox:
    description: "Run tox"
    parameters:
      env:
        type: string
    steps:
      - run:
          name: Preinstall phantomjs to work around an npm permission issue
          command: npm install -g phantomjs-prebuilt --unsafe-perm
      - run:
          name: Run tests via tox
          # Piping through cat does less buffering of the output but can
          # consume the exit code
          command: tox -e << parameters.env >> | cat; test ${PIPESTATUS[0]} -eq 0
  coverage:
    description: "Upload coverage"
    steps:
      - run:
          name: Install Codecov client
          command: pip install codecov==2.1.9
      - run:
          name: Upload coverage
          # Retry as codecov can be flaky
          command: for i in $(seq 1 10); do [ $i -gt 1 ] && echo "retrying $i" && sleep 5; codecov --required --disable search pycov gcov --root project --file .tox/coverage/py_coverage.xml .tox/coverage/cobertura-coverage.xml && s=0 && break || s=$?; done; (exit $s)

jobs:
  py36:
    executor: toxandnode
    steps:
      - checkout
      - dependencies
      - tox:
          env: py36
      - coverage
  py37:
    executor: toxandnode
    steps:
      - checkout
      - dependencies
      - tox:
          env: py37
      - coverage
  lint_and_docs:
    executor: toxandnode
    steps:
      - checkout
      - tox:
          env: flake8,lintclient
  # release:
  #   docker:
  #     - image: girder/tox-and-node
  #   steps:
  #     - checkout
  #     - deploy:
  #         name: Run tests via tox
  #         # Piping through cat does less buffering of the output but can
  #         # consume the exit code
  #         command: tox -e release | cat; test ${PIPESTATUS[0]} -eq 0

workflows:
  version: 2
  ci:
    jobs:
      - py36:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - gh-pages
      - py37:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - gh-pages
      - lint_and_docs:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - gh-pages
      # - release:
      #     requires:
      #       - py36
      #       - py37
      #       - lint_and_docs
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         only: master